package model.AM;

import model.AM.common.PwcOdmGradingTerryAM;

import oracle.adf.share.ADFContext;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 24 18:02:56 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcOdmGradingTerryAMImpl extends ApplicationModuleImpl implements PwcOdmGradingTerryAM {
    
    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        System.out.println("orgid = "+orgId);
        ADFContext.getCurrent().getSessionScope().put("user_id", userId);
        ADFContext.getCurrent().getSessionScope().put("org_id", orgId);
        ADFContext.getCurrent().getSessionScope().put("resp_id", respId);
        ADFContext.getCurrent().getSessionScope().put("resp_appl_id", respAppl);
    }
    /**
     * This is the default constructor (do not remove).
     */
    public PwcOdmGradingTerryAMImpl() {
    }

    /**
     * Container's getter for PwcOdmNGGradingHeadersVO1.
     * @return PwcOdmNGGradingHeadersVO1
     */
    public ViewObjectImpl getPwcOdmNGGradingHeadersVO1() {
        return (ViewObjectImpl)findViewObject("PwcOdmNGGradingHeadersVO1");
    }

    /**
     * Container's getter for PwcOdmNGGradingLinesVO1.
     * @return PwcOdmNGGradingLinesVO1
     */
    public ViewObjectImpl getPwcOdmNGGradingLinesVO1() {
        return (ViewObjectImpl)findViewObject("PwcOdmNGGradingLinesVO1");
    }

    /**
     * Container's getter for PwcOdmNGGradingHeadersVO2.
     * @return PwcOdmNGGradingHeadersVO2
     */
    public ViewObjectImpl getPwcOdmNGGradingHeadersVO2() {
        return (ViewObjectImpl)findViewObject("PwcOdmNGGradingHeadersVO2");
    }

    /**
     * Container's getter for PwcOdmNGGradingLinesVO2.
     * @return PwcOdmNGGradingLinesVO2
     */
    public ViewObjectImpl getPwcOdmNGGradingLinesVO2() {
        return (ViewObjectImpl)findViewObject("PwcOdmNGGradingLinesVO2");
    }

    /**
     * Container's getter for PwcOdmNGGradingHdrsLinesVL.
     * @return PwcOdmNGGradingHdrsLinesVL
     */
    public ViewLinkImpl getPwcOdmNGGradingHdrsLinesVL() {
        return (ViewLinkImpl)findViewLink("PwcOdmNGGradingHdrsLinesVL");
    }
}
